### ISSUE TITLE
add N arg to register preview next/previous

### ISSUE THREAD

**Issue by progfolio** [thierryvolpiatto/register-preview#1]
It may be useful to add an "N" arg to the `register-preview-next`/`previous` commands so a numeric arg can be passed to navigate N times.

**Comment by thierryvolpiatto** [comment]
Nicholas Vollmer ***@***.***> writes:

> It may be useful to add an "N" arg to the register-preview-next/previous commands so a numeric arg can be passed to navigate N times.

Done.  However IME this is rarely used, because it is visually hard to
count the number of lines we you want to jump to reach the desired
place after 3/5 so generally you have better time using repeatively
C-n/p.  If you count the number of key you have to type for e.g. C-u 3
<down>, it is the same as typing 3 times <down>, after it becomes faster
typing C-u <n> <down>, but if you remove the time elapsed to figure out
the prefix number you will have to type, hmm... often it is as fast as
quickly typing repeatively <down> or C-n.
Well that's my impression.

Thanks. 

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>

-- 
Thierry
